version: '3.8'

services:
  wireguard:
    depends_on:
      - unbound
      - pihole
    image: linuxserver/wireguard:latest
    container_name: wireguard
    expose:
      - 5000
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./volumes/wireguard/config:/config
      - /lib/modules:/lib/modules
    env_file: ./.env_wire
    networks:
      admin-subnet:
        ipv4_address: 100.100.100.3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    volumes:
      - ./volumes/wire_ui_data:/app/db
      - ./volumes/wireguard/config:/etc/wireguard/
    env_file: ./.env_wire
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

#  lazydocker:
#    image: lazyteam/lazydocker
#    dns:
#      - 127.0.0.11
#      - 100.100.100.9
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./volumes/lazydocker:/root/.config/lazydocker
#    networks:
#      admin-subnet:
#        ipv4_address: 100.100.100.5
#    logging:
#      driver: json-file
#      options:
#        max-size: "10m"
#        max-file: "3"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    dns:
      - 127.0.0.11
      - 100.100.100.9
    environment:
      PUID: 1000
      PGID: 1000
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.admin.lab`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=myresolver"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    volumes:
      - ./volumes/homepage/config:/app/config
      - ./volumes/homepage/services.yaml:/app/config/services.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      admin-subnet:
        ipv4_address: 100.100.100.6
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


# authelia:
#   image: authelia/authelia
#   container_name: authelia
#   aliases:
#     - "auth.lab"
#   dns:
#     - 127.0.0.11
#     - 100.100.100.9
#   volumes:
#     - ./volumes/authelia:/config
#   expose:
#     - 9091
#   restart: unless-stopped
#   networks:
#     admin-subnet:
#       ipv4_address: 100.100.100.7
#   logging:
#     driver: json-file
#     options:
#       max-size: "10m"
#       max-file: "3"

# traefik:
#   image: traefik:2.11
#   container_name: traefik
#   dns:
#     - 127.0.0.11
#     - 100.100.100.9
#   depends_on:
#     - step-ca
#   volumes:
#     - ./volumes/traefik:/etc/traefik
#     - ./volumes/step-ca/certs/root_ca.crt:/usr/local/share/ca-certificates/my_root_ca.crt      
#     - /var/run/docker.sock:/var/run/docker.sock
#     - ./volumes/traefik_config/traefik.yaml:/etc/traefik/traefik.yml
#   networks:
#     admin-subnet:
#       ipv4_address: 100.100.100.10
#   logging:
#     driver: json-file
#     options:
#       max-size: "10m"
#       max-file: "3"
#   env_file: ./.env_traefik
#   expose:
#     - 80
#     - 443

  step-ca:
    image: smallstep/step-ca
    dns:
      - 127.0.0.11
      - 100.100.100.9
    expose:
      - 9000
    volumes:
      - ./volumes/step-ca:/home/step
    networks:
      admin-subnet:
        aliases:
          - "ca.lab"
        ipv4_address: 100.100.100.11
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    expose:
      - 53
    volumes:
      - ./volumes/unbound:/opt/unbound/etc/unbound/
    networks:
      admin-subnet:
        ipv4_address: 100.100.100.8
    cap_add:
      - NET_ADMIN
    env_file: ./.env_pihole
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    expose:
     - 53
     - 67 # Se DHCP
     - 80
     - 22
     - 443
    dns:
      - 127.0.0.1
      - 100.100.100.8
    volumes:
      - ./volumes/pihole_data:/etc/pihole:rw 
      - ./volumes/pihole_custom_list/custom.list:/etc/pihole/custom.list   
    cap_add:
      - NET_ADMIN
    networks:
      admin-subnet:
        ipv4_address: 100.100.100.9
    env_file: ./.env_pihole
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
   admin-subnet:
    ipam:
      config:
        - subnet: 100.100.100.0/24
