
api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: admin-subnet
#  file:
#    filename: /dynamic-conf.yml
#    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: "admin.lab"
            sans:
              - "*.admin.lab"

certificatesResolvers:
  myresolver:
    acme:
      email: admin@example.com
      storage: /etc/traefik/acme/acme.json
      # For Lets Encrypt production use "https://acme-v02.api.letsencrypt.org/directory"
      caServer: "https://ca.admin.lab:9000/acme/acme/directory" # Uncomment and modify for step-ca or other custom CA
      httpChallenge:
        entryPoint: web

# Dynamic part for example

http:
  routers:
    # Dynamic routing
    my-router:
      rule: "Host(`example.com`)"
      service: my-service
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://your-service:80"

# You can Add middlewares ecc
